### ISSUE TITLE
get_qaly_data fails in trivial case

### ISSUE THREAD

**Issue by jaryaman** [tomMcGrath/rationalnews#6]
Using `global_prios/global_prios_simple.csv` breaks `main.py`, presumably because `score_articles.get_qaly_data` fails in the trivial case.

**Comment by sloomba** [comment]
Found the bug; yeah it wasn't working in the trivial case without any AND or OR. It should be working now in the issue6 branch. Closing this for now.

**Comment by jaryaman** [comment]
Do you want to check it works with the latest master branch (it almost certainly will) then merge your branch into master?

**Comment by sloomba** [comment]
Yes, I checked and it appears to work fine now; merged.
